Name = "SafeDNS"
Description = ''''''
URL = "https://www.ukfast.co.uk/dns-hosting.html"
Code = "safedns"
Since = "v4.6.0"

Example = '''
SAFEDNS_AUTH_TOKEN=xxxxxx \
lego --email myemail@example.com --dns safedns --domains my.example.org run
'''

[Configuration]
  [Configuration.Credentials]
    SAFEDNS_AUTH_TOKEN = "Authentication token"
  [Configuration.Additional]
    SAFEDNS_TTL = "TXT record TTL"
    SAFEDNS_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    SAFEDNS_API_TIMEOUT = "API request timeout in seconds"
    SAFEDNS_POLLING_INTERVAL = "Time to wait for initial check"

[Links]
  API = "https://developers.ukfast.io/documentation/safedns"
